theme: jekyll-theme-minimal

title: Tinus EngOps Wiki

description: OpsaC - Operating as PowerShell code
[it.martin-walther.ch](https://it.martin-walther.ch)

logo: /assets/PsEngOps.png

show_downloads: false
